import { CompleteDashboardData } from '../types/dashboard';

export const mockCompleteDashboardData: CompleteDashboardData = {
  lastUpdated: '12 min ago',
  systemStatus: 'Operational',
  stats: [
    {
      id: 'stat-datasets',
      title: 'Active Datasets',
      value: '128',
      supportingText: '+8 this month',
      changeDirection: 'up',
      status: 'positive',
      iconType: 'database',
    },
    {
      id: 'stat-floats',
      title: 'Active Floats',
      value: '2,486',
      supportingText: 'ARGO + moored platforms',
      changeDirection: 'neutral',
      status: 'normal',
      iconType: 'floats',
    },
    {
      id: 'stat-update',
      title: 'Latest Update',
      value: '12 min ago',
      supportingText: 'All major feeds synchronized',
      changeDirection: 'neutral',
      status: 'calibrated',
      iconType: 'clock',
    },
    {
      id: 'stat-regions',
      title: 'Monitored Regions',
      value: '24',
      supportingText: 'Indian Ocean + coastal zones',
      changeDirection: 'neutral',
      status: 'normal',
      iconType: 'map',
    },
    {
      id: 'stat-temperature',
      title: 'Avg Surface Temperature',
      value: '28.4°C',
      supportingText: '+0.3°C anomaly',
      changeDirection: 'up',
      status: 'warning',
      iconType: 'thermometer',
    },
    {
      id: 'stat-alerts',
      title: 'Active Alerts',
      value: '07',
      supportingText: '2 high priority',
      changeDirection: 'down',
      status: 'critical',
      iconType: 'alert',
    },
  ],
  regionalOverview: {
    totalBasinObservations: 1920,
    regions: [
      {
        id: 'reg-as',
        name: 'Arabian Sea',
        observationsCount: 542,
        activeAlertsCount: 1,
        averageSstCelsius: 28.1,
        meanWaveHeightMeters: 2.8,
        coordinates: { lat: 15.0, lng: 65.0 },
      },
      {
        id: 'reg-bob',
        name: 'Bay of Bengal',
        observationsCount: 718,
        activeAlertsCount: 1,
        averageSstCelsius: 29.4,
        meanWaveHeightMeters: 2.1,
        coordinates: { lat: 14.5, lng: 88.0 },
      },
      {
        id: 'reg-eio',
        name: 'Equatorial Indian Ocean',
        observationsCount: 389,
        activeAlertsCount: 0,
        averageSstCelsius: 29.8,
        meanWaveHeightMeters: 1.6,
        coordinates: { lat: 0.0, lng: 78.0 },
      },
      {
        id: 'reg-sio',
        name: 'Southern Indian Ocean',
        observationsCount: 271,
        activeAlertsCount: 0,
        averageSstCelsius: 18.2,
        meanWaveHeightMeters: 3.4,
        coordinates: { lat: -25.0, lng: 75.0 },
      },
    ],
  },
  recentActivities: [
    {
      id: 'act-1',
      title: 'ARGO float IN2026-0842 transmitted a new profile',
      timestamp: '8 min ago',
      type: 'argo',
      details: 'Depth profile 0-2000m CTD validated (Arabian Sea transect)',
    },
    {
      id: 'act-2',
      title: 'Bay of Bengal observation dataset synchronized',
      timestamp: '21 min ago',
      type: 'sync',
      details: 'RAMA & OMNI array 06:00 UTC batch processed (718 records)',
    },
    {
      id: 'act-3',
      title: 'Wave-height alert threshold updated',
      timestamp: '34 min ago',
      type: 'alert',
      details: 'Threshold adjusted to 3.0m along Southwest peninsular coast',
    },
    {
      id: 'act-4',
      title: 'Coastal station IN-CST-042 reported new measurements',
      timestamp: '1 hour ago',
      type: 'station',
      details: 'Kochi radar and acoustic tide gauge report normal tidal swing',
    },
    {
      id: 'act-5',
      title: 'Regional forecast dataset refreshed',
      timestamp: '2 hours ago',
      type: 'forecast',
      details: 'ROMS hydrodynamic and WaveWatch III 24h run published',
    },
  ],
  systemDataStatus: [
    {
      id: 'sys-argo',
      name: 'ARGO Network',
      status: 'Operational',
      coveragePercent: 98,
      iconType: 'argo',
    },
    {
      id: 'sys-buoy',
      name: 'Moored Buoys',
      status: 'Operational',
      coveragePercent: 94,
      iconType: 'buoy',
    },
    {
      id: 'sys-tide',
      name: 'Coastal Tide Gauges',
      status: 'Operational',
      coveragePercent: 96,
      iconType: 'tide',
    },
    {
      id: 'sys-satellite',
      name: 'Satellite Feeds',
      status: 'Operational',
      coveragePercent: 91,
      iconType: 'satellite',
    },
    {
      id: 'sys-forecast',
      name: 'Forecast Models',
      status: 'Operational',
      latestRun: '18 min ago',
      iconType: 'model',
    },
  ],
  alertSummary: {
    totalAlerts: 7,
    highPriority: 2,
    mediumPriority: 3,
    informational: 2,
    alerts: [
      {
        id: 'alt-high-1',
        title: 'Elevated wave height detected — Arabian Sea',
        description: 'Wave rider buoys offshore Ratnagiri report significant swell heights reaching 3.8 meters. Coastal marine advisories dispatched.',
        priority: 'high',
        region: 'Arabian Sea (West Coast)',
        timestamp: '18 min ago',
      },
      {
        id: 'alt-high-2',
        title: 'Sea surface temperature anomaly — Bay of Bengal',
        description: 'Persistent thermal anomaly of +1.4°C detected in central Bay of Bengal basin. Elevated risk of convective system development.',
        priority: 'high',
        region: 'Central Bay of Bengal',
        timestamp: '32 min ago',
      },
      {
        id: 'alt-med-1',
        title: 'Ocean current shear advisory — Equatorial Channel',
        description: 'Zonal surface currents exceeding 2.4 knots recorded along 0°N transect. Shipping routing notice issued.',
        priority: 'medium',
        region: 'Equatorial Indian Ocean',
        timestamp: '1 hour ago',
      },
    ],
  },
  quickAccess: [
    {
      id: 'qa-explore',
      title: 'Explore',
      description: 'Interactive ocean visualization',
      route: '/explore',
      icon: 'explore',
    },
    {
      id: 'qa-obs',
      title: 'Observations',
      description: 'Browse real-time and historical observations',
      route: '/observations',
      icon: 'observations',
    },
    {
      id: 'qa-compare',
      title: 'Compare',
      description: 'Compare models with observations',
      route: '/compare',
      icon: 'compare',
    },
    {
      id: 'qa-analytics',
      title: 'Analytics',
      description: 'Analyze ocean trends and anomalies',
      route: '/analytics',
      icon: 'analytics',
    },
  ],
};
