import {
  OceanObservationRecord,
  DepthProfilePoint,
  RecentMeasurementItem,
  ObservationPlatformSummary,
} from '../types/observation';

export const mockObservationSummary: ObservationPlatformSummary = {
  totalPlatforms: 2486,
  lastSynchronized: '12 min ago',
  filterCounts: {
    active: 2314,
    warning: 98,
    inactive: 74,
  },
};

export const mockObservationRecords: OceanObservationRecord[] = [
  {
    id: 'OBS-IN2026-0842',
    instrumentId: 'IN2026-0842',
    name: 'Apex Profiling Float IN2026-0842',
    platform: 'ARGO Float',
    type: 'argo-float',
    region: 'Arabian Sea',
    basin: 'Arabian Sea',
    coordinates: { latitude: 15.2, longitude: 67.4 },
    depthMeters: 1000,
    depthCategory: '500-1000m',
    lastPing: '12 min ago',
    timestamp: '2026-09-11 12:15 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 28.1,
      salinityPsu: 35.4,
      pressureDbar: 1025,
      dissolvedOxygenMgL: 5.6,
      currentSpeedKnots: 1.2,
    },
    status: 'active',
    batteryPercent: 92,
  },
  {
    id: 'OBS-IN2026-0917',
    instrumentId: 'IN2026-0917',
    name: 'Bio-Argo Profiler IN2026-0917',
    platform: 'ARGO Float',
    type: 'argo-float',
    region: 'Bay of Bengal',
    basin: 'Bay of Bengal',
    coordinates: { latitude: 14.8, longitude: 87.2 },
    depthMeters: 1200,
    depthCategory: '>1000m',
    lastPing: '21 min ago',
    timestamp: '2026-09-11 12:06 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 29.1,
      salinityPsu: 34.8,
      chlorophyllMgM3: 0.42,
      dissolvedOxygenMgL: 6.1,
      currentSpeedKnots: 0.9,
    },
    status: 'active',
    batteryPercent: 86,
  },
  {
    id: 'OBS-IN-MB-021',
    instrumentId: 'IN-MB-021',
    name: 'Deep Sea Moored Buoy IN-MB-021',
    platform: 'Moored Buoy',
    type: 'moored-buoy',
    region: 'Arabian Sea',
    basin: 'Arabian Sea',
    coordinates: { latitude: 11.5, longitude: 70.3 },
    depthMeters: 10,
    depthCategory: '0-100m',
    lastPing: '34 min ago',
    timestamp: '2026-09-11 11:53 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 28.0,
      salinityPsu: 35.1,
      significantWaveHeightMeters: 2.7,
      currentSpeedKnots: 1.8,
    },
    status: 'active',
    batteryPercent: 95,
  },
  {
    id: 'OBS-IN-WR-014',
    instrumentId: 'IN-WR-014',
    name: 'Offshore Wave Rider IN-WR-014',
    platform: 'Wave Rider',
    type: 'wave-rider-buoy',
    region: 'Bay of Bengal',
    basin: 'Bay of Bengal',
    coordinates: { latitude: 13.1, longitude: 82.5 },
    depthMeters: 0,
    depthCategory: 'surface',
    lastPing: '41 min ago',
    timestamp: '2026-09-11 11:46 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 29.3,
      salinityPsu: 34.7,
      significantWaveHeightMeters: 3.8,
      currentSpeedKnots: 2.4,
    },
    status: 'warning',
    batteryPercent: 78,
  },
  {
    id: 'OBS-IN-CST-042',
    instrumentId: 'IN-CST-042',
    name: 'Chennai Port Acoustic Tide Gauge IN-CST-042',
    platform: 'Coastal Tide Gauge',
    type: 'tide-gauge',
    region: 'Bay of Bengal',
    basin: 'Bay of Bengal',
    coordinates: { latitude: 13.08, longitude: 80.29 },
    depthMeters: 0,
    depthCategory: 'surface',
    lastPing: '5 min ago',
    timestamp: '2026-09-11 12:22 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 29.9,
      salinityPsu: 34.9,
      seaLevelAnomalyCm: 14.2,
      currentSpeedKnots: 0.8,
    },
    status: 'active',
    batteryPercent: 100,
  },
  {
    id: 'OBS-IN-MB-008',
    instrumentId: 'IN-MB-008',
    name: 'INCOIS OMNI Moored Buoy BD08',
    platform: 'Moored Buoy',
    type: 'moored-buoy',
    region: 'Bay of Bengal',
    basin: 'Bay of Bengal',
    coordinates: { latitude: 18.2, longitude: 89.67 },
    depthMeters: 2150,
    depthCategory: '>1000m',
    lastPing: '8 min ago',
    timestamp: '2026-09-11 12:19 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 29.8,
      salinityPsu: 32.4,
      significantWaveHeightMeters: 2.1,
      currentSpeedKnots: 1.4,
    },
    status: 'active',
    batteryPercent: 94,
  },
  {
    id: 'OBS-IN-WR-022',
    instrumentId: 'IN-WR-022',
    name: 'Kochi Coastal Wave Rider IN-WR-022',
    platform: 'Wave Rider',
    type: 'wave-rider-buoy',
    region: 'Arabian Sea',
    basin: 'Arabian Sea',
    coordinates: { latitude: 9.98, longitude: 76.12 },
    depthMeters: 45,
    depthCategory: '0-100m',
    lastPing: '15 min ago',
    timestamp: '2026-09-11 12:12 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 29.2,
      salinityPsu: 34.6,
      significantWaveHeightMeters: 3.4,
      currentSpeedKnots: 2.6,
    },
    status: 'active',
    batteryPercent: 97,
  },
  {
    id: 'OBS-IN2026-0731',
    instrumentId: 'IN2026-0731',
    name: 'Equatorial Bio-Argo IN2026-0731',
    platform: 'ARGO Float',
    type: 'argo-float',
    region: 'Equatorial Indian Ocean',
    basin: 'Equatorial Indian Ocean',
    coordinates: { latitude: 1.45, longitude: 80.22 },
    depthMeters: 1980,
    depthCategory: '>1000m',
    lastPing: '48 min ago',
    timestamp: '2026-09-11 11:39 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 30.1,
      salinityPsu: 34.8,
      chlorophyllMgM3: 0.35,
      dissolvedOxygenMgL: 5.1,
    },
    status: 'active',
    batteryPercent: 82,
  },
  {
    id: 'OBS-IN2026-1104',
    instrumentId: 'IN2026-1104',
    name: 'Deep Apex Profiler IN2026-1104',
    platform: 'ARGO Float',
    type: 'argo-float',
    region: 'Southern Indian Ocean',
    basin: 'Southern Indian Ocean',
    coordinates: { latitude: -24.12, longitude: 75.89 },
    depthMeters: 2000,
    depthCategory: '>1000m',
    lastPing: '3 hours ago',
    timestamp: '2026-09-11 09:20 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 16.4,
      salinityPsu: 34.9,
      dissolvedOxygenMgL: 7.2,
    },
    status: 'inactive',
    batteryPercent: 41,
  },
  {
    id: 'OBS-RV-SAGAR-KANYA',
    instrumentId: 'RV-SK-01',
    name: 'RV Sagar Kanya Underway Sensor Array',
    platform: 'Ship Observation',
    type: 'ship-observation',
    region: 'Equatorial Indian Ocean',
    basin: 'Equatorial Indian Ocean',
    coordinates: { latitude: 4.2, longitude: 73.5 },
    depthMeters: 0,
    depthCategory: 'surface',
    lastPing: '28 min ago',
    timestamp: '2026-09-11 11:59 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 29.6,
      salinityPsu: 35.3,
      currentSpeedKnots: 1.5,
      dissolvedOxygenMgL: 5.9,
    },
    status: 'active',
    batteryPercent: 100,
  },
  {
    id: 'OBS-IN-CST-019',
    instrumentId: 'IN-CST-019',
    name: 'Goa Mormugao Tide Station IN-CST-019',
    platform: 'Coastal Tide Gauge',
    type: 'tide-gauge',
    region: 'Arabian Sea',
    basin: 'Arabian Sea',
    coordinates: { latitude: 15.4, longitude: 73.8 },
    depthMeters: 0,
    depthCategory: 'surface',
    lastPing: '19 min ago',
    timestamp: '2026-09-11 12:08 UTC',
    parameters: {
      seaSurfaceTemperatureCelsius: 28.5,
      salinityPsu: 35.8,
      seaLevelAnomalyCm: 8.6,
    },
    status: 'active',
    batteryPercent: 99,
  },
];

// Profile data for depth visualization (0m -> 1000m)
export const mockDepthProfiles: Record<string, DepthProfilePoint[]> = {
  'IN2026-0842': [
    { depthMeters: 0, temperatureCelsius: 28.4, salinityPsu: 35.2, pressureDbar: 1, dissolvedOxygenMgL: 5.8 },
    { depthMeters: 50, temperatureCelsius: 28.0, salinityPsu: 35.3, pressureDbar: 51, dissolvedOxygenMgL: 5.6 },
    { depthMeters: 100, temperatureCelsius: 27.4, salinityPsu: 35.4, pressureDbar: 102, dissolvedOxygenMgL: 5.2 },
    { depthMeters: 200, temperatureCelsius: 25.8, salinityPsu: 35.6, pressureDbar: 204, dissolvedOxygenMgL: 4.4 },
    { depthMeters: 300, temperatureCelsius: 23.9, salinityPsu: 35.7, pressureDbar: 307, dissolvedOxygenMgL: 3.8 },
    { depthMeters: 500, temperatureCelsius: 19.8, salinityPsu: 35.8, pressureDbar: 512, dissolvedOxygenMgL: 2.9 },
    { depthMeters: 700, temperatureCelsius: 15.7, salinityPsu: 35.9, pressureDbar: 718, dissolvedOxygenMgL: 2.4 },
    { depthMeters: 1000, temperatureCelsius: 11.2, salinityPsu: 36.1, pressureDbar: 1025, dissolvedOxygenMgL: 2.1 },
  ],
  default: [
    { depthMeters: 0, temperatureCelsius: 29.0, salinityPsu: 34.8, pressureDbar: 1, dissolvedOxygenMgL: 6.0 },
    { depthMeters: 50, temperatureCelsius: 28.7, salinityPsu: 34.9, pressureDbar: 51, dissolvedOxygenMgL: 5.8 },
    { depthMeters: 100, temperatureCelsius: 27.9, salinityPsu: 35.1, pressureDbar: 102, dissolvedOxygenMgL: 5.3 },
    { depthMeters: 200, temperatureCelsius: 26.1, salinityPsu: 35.3, pressureDbar: 204, dissolvedOxygenMgL: 4.6 },
    { depthMeters: 300, temperatureCelsius: 24.2, salinityPsu: 35.5, pressureDbar: 307, dissolvedOxygenMgL: 3.9 },
    { depthMeters: 500, temperatureCelsius: 20.1, salinityPsu: 35.7, pressureDbar: 512, dissolvedOxygenMgL: 3.1 },
    { depthMeters: 700, temperatureCelsius: 16.0, salinityPsu: 35.9, pressureDbar: 718, dissolvedOxygenMgL: 2.6 },
    { depthMeters: 1000, temperatureCelsius: 11.8, salinityPsu: 36.0, pressureDbar: 1025, dissolvedOxygenMgL: 2.2 },
  ],
};

// Recent measurement bursts
export const mockRecentMeasurements: RecentMeasurementItem[] = [
  { id: 'm-1', timeAgo: '12 min ago', depthMeters: 0, temperatureCelsius: 28.4, salinityPsu: 35.2, pressureDbar: 1, quality: 'Good' },
  { id: 'm-2', timeAgo: '18 min ago', depthMeters: 50, temperatureCelsius: 28.0, salinityPsu: 35.3, pressureDbar: 51, quality: 'Good' },
  { id: 'm-3', timeAgo: '27 min ago', depthMeters: 100, temperatureCelsius: 27.4, salinityPsu: 35.4, pressureDbar: 102, quality: 'Good' },
  { id: 'm-4', timeAgo: '41 min ago', depthMeters: 200, temperatureCelsius: 25.8, salinityPsu: 35.6, pressureDbar: 204, quality: 'Good' },
  { id: 'm-5', timeAgo: '58 min ago', depthMeters: 300, temperatureCelsius: 23.9, salinityPsu: 35.7, pressureDbar: 307, quality: 'Good' },
];

export const mockObservationData = mockObservationRecords;
